- name: Configure hosts & deploy application
  hosts: app
  become: true
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/sroot/reddit
      version: monolith
    notify: reload puma
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/sroot/reddit
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted